[SOK-22] User profile page
Timur233/falcon-tanks pull request #13
Opened 2024-10-01 05:48 UTC by VladToby

[### Какую задачу решаем](https://linear.app/sokoly/issue/SOK-22/sverstat-stranicu-polzovatelya)

### Скриншоты/видяшка (если есть)
<img width="1440" alt="Снимок экрана 2024-10-01 в 09 46 44" src="https://github.com/user-attachments/assets/1e783c9a-e019-4ee9-abb3-97f2466a77f0">

### TBD (если есть)

2024-10-01 11:04 UTC, Timur233 requested changes
Привет! Классно придумал как сделать редактирование информации о пользователе 👍
У меня много правок по верстке и есть предложение добавить компонент для уведомлений пользователя. Я сейчас накидаю дизайн, если ты занят могу сам компонент сверстать, ты просто к себе затянешь.

Комментов много, если что пиши в тг.

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/components/ui/Image/Image.tsx
> +export const Image = (props: ImageProps) => {
Честно говоря, не понимаю зачем нужен этот компонент, выглядит как будто проще написать img

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/components/ui/Avatar/Avatar.tsx
> +export const AVATAR_SRC = 'https://ya-praktikum.tech/api/v2/resources'
Эту константу стоит вынести в env файл, обсуди с Георгием.

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/components/ui/Avatar/Avatar.tsx
> +  onAvatarChange: (file: File) => void
В этом компоненте ничего больше нельзя поменять, я думаю проще переименовать onAvatarChange > onChange

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/components/ui/Avatar/Avatar.tsx
> +      className={`${containerClassName}`}
containerClassName, этот проп не обязательный, если его не указать вообще ничего не будет.
Нужно добавить класс по умолчанию. Да и в целом стили по нему можно в отдельный файл вынести.

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/components/ui/Avatar/Avatar.tsx
> +      onMouseLeave={() => setIsHovered(false)}>
Кажется ты чуть-чуть усложнил)) Как по мне проще сделать так:

.avatar-editor {
    &::hover {
        .avatar-editor__overlay {
            display: block;
        }
    }
}

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/components/ui/Avatar/Avatar.tsx
> +          {/* Здесь можно добавить иконку или текст для placeholder */}
Нужно сразу добавить placeholder, я когда открыл страницу первым делом увидел битое изображение.
Возьми из интернета любой placeholder для аватарки.

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/components/ui/Avatar/Avatar.tsx
> +      {isHovered && (
Вот эту механику лучше вынести в css.

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/components/ui/Avatar/Avatar.tsx
> +          />
Отсюда лучше убрать компонент кнопки, лучше просто добавить стандартный <button/> и стилизовать ее, чем переназначать все стили компонента Button

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/components/ui/Avatar/Avatar.tsx
> +        accept="image/*"
АПИ не поддерживает SVG, нужно указать вручную доступные форматы
<img width="603" alt="image" src="https://github.com/user-attachments/assets/357a0aa4-9bb8-4b10-9095-9cd0742d265a">

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/components/ui/Form/Form.tsx
> +    <form onSubmit={onSubmit} className={`form ${className}`}>
Класс form лучше переименовать, во что-то более специфичное, что бы избежать конфликтов. 
Можно что-то в духе form-fields

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/components/ui/Input/Input.scss
> +
Забыл указать размер шрифта

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/components/ui/Input/Input.scss
> +  width: 301px;
Эти инпуты будут использоваться на других страницах, ширину лучше сделать 100% или вовсе убрать. Можешь указать ширину для родителя формы и сделать инпут и форму 100%

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/components/ui/Input/Input.tsx
> +      className={className}
По умолчанию добавь класс input-default а если это какой-то специфический элемент, ребята будут передавать свои классы пропсами. 
Например: 
По умолчанию "input-default", а для своей формы могу сделать так "input-default my-form__input"

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/components/ui/Input/Input.tsx
> +    <input
Вот тут наверное стоит добавить обертку, возможно нужно будет добавить иконку или сообщение об ошибке.
<div class="default-input">
<input class="default-input__field">
</div>

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.tsx
> +      <div className={'profile-page-layout__profile-page'}>
profile-page-layout и profile-page-layout__profile-page выполняют одну и ту же функцию. 
Просто сделай 
<\div class="profile-page">
<\div class="profile-page__sidebar"/>
<\div class="profile-page__content"/>
<\/div>

У тебя стили станут проще, меньше будет вложенности и код станет менее запутанным

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.tsx
> +            alt={'Profile Sidebar'}
Вот это изображение лучше сделать background'ом, и разместить на .profile-page, в левый нижний угол. Так оно всегда будет внизу страницы, не будет влиять на скролл и отображение других элементов.
Отдельно вытащил его в фигме.
<img width="460" alt="image" src="https://github.com/user-attachments/assets/c4af1584-7d61-4ac0-a3c3-a1d90135812f">

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.tsx
> +                'profile-page-layout__profile-page__profile-container__success-message'
Давай задизайним уведомления для пользователя, и сделаем отдельный компонент

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.tsx
> +      console.error('Ошибка при обновлении аватара:', error)
Я старался имитировать эту ошибку, а точнее отправлял svg который апи не принимает, и не разу не смог получить эту ошибку.

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.tsx
> +  const handleInputChange =
Прикольно заморочился 👍

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.tsx
> +      setError('Ошибка при сохранении данных')
Всегда проходит без ошибок, хотя запрос валится если допустим отправить не валидный номер

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.tsx
> +    setIsLoading(true)
Я делал прелоадер, можно будет поставить когда будем сливать все в рабочую ветку.

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.scss
> +.profile-page-layout {
Можно убрать

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.scss
> +  &__profile-page {
Можно оставить только { display: flex }

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.scss
> +    &__sidebar {
В целом если ты изображение на странице вынесешь в bg для profile-page, то сайдбар можно будет полностью убрать. Я писал об этом ранее к файлу Profile.tsx

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.scss
> +    &__profile-container {
Вот тут есть еще мысль, напишу в комменте к файлу

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.scss
> +        margin-bottom: 2rem;
По макету отступ больше.

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.scss
> +      &__profile-avatar {
Все что касается компонента "аватар" лучше вынести в отдельный файл к компоненту

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.scss
> +        margin: 0 auto 2rem;
Отступ снизу в макете больше

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/components/ui/Input/Input.tsx
> +    <input
Насколько я понял, у тебя в форме есть еще обертка form-group, может в таком случае сделать компонент form-group вместо input. 
У него будет больше функциональности которую в последствии можно будет переиспользовать.

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.scss
> +          margin-bottom: 0.5rem;
Из-за инпутов в строке у тебя получился больший отступ между строк. Так что этот маржин можно убрать

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.scss
> +        margin: 0 auto;
Перед кнопками нужен отступ, как в макете

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.scss
> +          margin-bottom: 2rem;
Тут отступ больше чем в макете

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.scss
> +          margin-bottom: 2rem;
Тут тоже отступ виликоват

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.scss
> +        button {
Я что-то не нашел этот элемент на странице

2024-10-01 11:04 UTC, Timur233 commented on packages/client/src/pages/Profile/Profile.tsx
По верстке у тебя получилась большая, сложная вложенность, плюс можно использовать систему гридов из проекта, да и в целом уменьшить количество кода. Я накидаю вариант, закреплю в этом сообщении. 
[Profile.tsx.zip](https://github.com/user-attachments/files/17203904/Profile.tsx.zip)

2024-10-01 17:37 UTC, gloginov reviewed
Есть крутые решения над которыми задумался

2024-10-01 17:37 UTC, gloginov commented on packages/client/src/pages/Profile/Profile.scss
> +      &__image {
У меня из-за этой картинки двойной скролл на странице

<img width="1186" alt="Screenshot 2024-10-01 at 22 06 27" src="https://github.com/user-attachments/assets/ab890992-29bd-460b-a681-7006c7f7d4c0">

2024-10-01 17:37 UTC, gloginov commented on packages/client/src/pages/Profile/Profile.scss
> +.profile-page-layout {
В принципе при наложении макета (при разрешении 1512 x 982) есть расхождения

Советую для проверки с макетом плагин для chrome:
https://chromewebstore.google.com/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi?hl=ru

<img width="1167" alt="Screenshot 2024-10-01 at 22 09 35" src="https://github.com/user-attachments/assets/465306ae-848f-4564-a3de-9e9e9ce63fda">

2024-10-01 17:37 UTC, gloginov commented on packages/client/src/pages/Profile/Profile.scss
> +          border: 5px solid #313131;
Лучше перенести все цвета в vars.scss и использовать переменные. Представь как удобно менять все цвета меняя его в одном месте.

2024-10-01 17:37 UTC, gloginov commented on packages/client/src/pages/Profile/Profile.tsx
> +          {isEditable && (
Тут можно тернарными операторами так сделать: если ? это : то
{true ? 
  <button text="save">
    :
  <button text="change">
}

2024-10-01 17:37 UTC, gloginov commented on packages/client/src/pages/Profile/Profile.tsx
> +import ProfileSidebarImg from '../../assets/images/profile-sidebar.png'
Для картинок из /assets  можно тоже добавить короткую запись в конфиге @/assets/images

2024-10-01 19:23 UTC, VladToby commented on packages/client/src/components/ui/Avatar/Avatar.tsx
> +  onAvatarChange: (file: File) => void
Поправил

2024-10-01 19:23 UTC, VladToby commented on packages/client/src/components/ui/Avatar/Avatar.tsx
> +      className={`${containerClassName}`}
Поправил

2024-10-01 19:23 UTC, VladToby commented on packages/client/src/components/ui/Avatar/Avatar.tsx
> +      onMouseLeave={() => setIsHovered(false)}>
Есть такое) 
Исправил

2024-10-01 19:23 UTC, VladToby commented on packages/client/src/components/ui/Avatar/Avatar.tsx
> +          {/* Здесь можно добавить иконку или текст для placeholder */}
Добавил

2024-10-01 19:23 UTC, VladToby commented on packages/client/src/components/ui/Avatar/Avatar.tsx
> +      {isHovered && (
Сделано

2024-10-01 19:24 UTC, VladToby commented on packages/client/src/components/ui/Avatar/Avatar.tsx
> +          />
Изменил

2024-10-01 19:24 UTC, VladToby commented on packages/client/src/components/ui/Avatar/Avatar.tsx
> +        accept="image/*"
Исправил

2024-10-01 19:24 UTC, VladToby commented on packages/client/src/components/ui/Form/Form.tsx
> +    <form onSubmit={onSubmit} className={`form ${className}`}>
Сделано

2024-10-01 19:24 UTC, VladToby commented on packages/client/src/pages/Profile/Profile.tsx
> +      <div className={'profile-page-layout__profile-page'}>
Поправил

2024-10-01 19:25 UTC, VladToby commented on packages/client/src/pages/Profile/Profile.scss
> +.profile-page-layout {
Сделал

2024-10-01 19:26 UTC, VladToby commented on packages/client/src/pages/Profile/Profile.scss
> +          border: 5px solid #313131;
Исправил

2024-10-01 19:26 UTC, VladToby commented on packages/client/src/pages/Profile/Profile.tsx
> +          {isEditable && (
Исправил

2024-10-01 21:10 UTC, VladToby commented on packages/client/src/pages/Profile/Profile.scss
> +      &__profile-avatar {
Сделано

2024-10-02 02:42 UTC, gloginov approved these changes

2024-10-02 05:11 UTC, VladToby commented on packages/client/src/components/ui/Input/Input.scss
> +
Исправил

2024-10-02 05:11 UTC, VladToby commented on packages/client/src/components/ui/Input/Input.scss
> +  width: 301px;
Исправил

2024-10-02 05:11 UTC, VladToby commented on packages/client/src/components/ui/Input/Input.tsx
> +      className={className}
Сделано

2024-10-02 05:11 UTC, VladToby commented on packages/client/src/components/ui/Input/Input.tsx
> +    <input
Добавил

2024-10-02 05:12 UTC, VladToby commented on packages/client/src/pages/Profile/Profile.tsx
> +    setIsLoading(true)
Пока убрал

2024-10-02 05:12 UTC, VladToby commented on packages/client/src/pages/Profile/Profile.scss
> +        margin-bottom: 2rem;
Поправил

2024-10-02 05:12 UTC, VladToby commented on packages/client/src/pages/Profile/Profile.scss
> +        margin: 0 auto 2rem;
Поправил

2024-10-02 05:12 UTC, VladToby commented on packages/client/src/pages/Profile/Profile.scss
> +          margin-bottom: 0.5rem;
Поправил

2024-10-02 05:12 UTC, VladToby commented on packages/client/src/pages/Profile/Profile.scss
> +        margin: 0 auto;
Поправил

2024-10-02 05:12 UTC, VladToby commented on packages/client/src/pages/Profile/Profile.scss
> +          margin-bottom: 2rem;
Поправил

2024-10-02 05:12 UTC, VladToby commented on packages/client/src/pages/Profile/Profile.scss
> +          margin-bottom: 2rem;
Поправил

2024-10-02 05:13 UTC, VladToby commented on packages/client/src/pages/Profile/Profile.scss
> +        button {
Исправил

2024-10-02 09:19 UTC, VladToby commented on packages/client/src/pages/Profile/Profile.tsx
> +            alt={'Profile Sidebar'}
Исправил

2024-10-02 09:20 UTC, VladToby commented on packages/client/src/pages/Profile/Profile.scss
> +  &__profile-page {
Сделано

2024-10-02 09:20 UTC, VladToby commented on packages/client/src/pages/Profile/Profile.scss
> +    &__sidebar {
Убрал

2024-10-02 13:08 UTC, shamemask approved these changes
Попробовал, работает с апи яндекса, отображение симпотичное!

2024-10-02 21:44 UTC, VladToby commented on packages/client/src/components/ui/Avatar/Avatar.tsx
> +export const AVATAR_SRC = 'https://ya-praktikum.tech/api/v2/resources'
Перенёс

2024-10-02 21:45 UTC, VladToby commented on packages/client/src/pages/Profile/Profile.tsx
> +      console.error('Ошибка при обновлении аватара:', error)
Исправил

2024-10-02 21:45 UTC, VladToby commented on packages/client/src/pages/Profile/Profile.tsx
> +      setError('Ошибка при сохранении данных')
Исправил

2024-10-03 06:07 UTC, Timur233 approved these changes
Получилось отлично! 
Единственное, нужно ограничить ширину инпута, при редактировании информации на странице профиля)

2024-10-03 06:50 UTC, kyzinatra commented on packages/client/src/components/ui/Avatar/Avatar.scss
> +
Мне кажется, что такие цвета лучше вынести в константы

2024-10-03 06:50 UTC, kyzinatra commented on packages/client/src/components/ui/Avatar/Avatar.tsx
> +      const fileUrl = URL.createObjectURL(file)
Логику с генерацией url я бы вынес в отдельный хук

2024-10-03 06:52 UTC, kyzinatra commented on packages/client/src/layouts/PrivateLayout/PrivateLayout.tsx
>    // }, [user])
Лишние логи стоит убрать

2024-10-03 06:53 UTC, kyzinatra approved these changes
Отличная работа! Хорошая верстка страниц для пользователя. Понравилось, что вы выделяете Интпуты в отдельные компоненты. В целом, хорошо организована логика в компонентах. Так что ваша работа принята! Желаю успехов в дальнейшем обучении!

2024-10-03 08:01 UTC, merged