Test
Timur233/falcon-tanks pull request #16
Opened 2024-10-05 11:28 UTC by k0ndratov

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-10-06 18:27 UTC, VladToby requested changes
Отличная работа! Страница форума выглядит очень хорошо! Есть несколько моментов, которые стоит исправить сразу.

2024-10-06 18:27 UTC, VladToby commented on packages/client/src/components/ui/Button/CompactButton.scss
> +      border-top: 52x solid #999999;
Судя по всему опечатка, нужно исправить
Также лучше использовать переменную для цвета

2024-10-06 18:27 UTC, VladToby commented on packages/client/src/components/ui/Button/CompactButton.scss
> +    border-bottom: 2px solid #999999;
Цвета стоит занести в переменную и использовать её

2024-10-06 18:27 UTC, VladToby commented on packages/client/src/components/ui/Button/CompactButton.scss
> +      border-bottom: 2px solid $c_white;
Лучше создать переменную для этого цвета и использовать её, если цвет нужно будет изменить, то будет проще менять цвет конкретного бордера

2024-10-06 18:27 UTC, VladToby commented on packages/client/src/components/ui/Button/CompactButton.scss
> +      color: #242424;
Также стоит занести цвет в переменную

2024-10-06 18:27 UTC, VladToby commented on packages/client/src/pages/Forum/Forum.scss
> +    background-image: url('@/assets/images/destroyed-tanks.png');
Картинка перекрывает темы
<img width="556" alt="Снимок экрана 2024-10-06 в 22 08 19" src="https://github.com/user-attachments/assets/e39195bd-5b88-4ea7-bda4-717414adcddb">

2024-10-06 18:27 UTC, VladToby commented on packages/client/src/components/ui/BreadCrumbs/BreadCrumbs.scss
> +    color: $c_white;
Лучше использовать конкретную переменную для цвета.

2024-10-06 18:27 UTC, VladToby commented on packages/client/src/components/ui/Card/Card.scss
> +  background-color: #5e5e5e;
Цвета стоит занести в переменные

2024-10-06 18:27 UTC, VladToby commented on packages/client/src/components/ui/Card/Card.scss
> +    background-color: #101010;
Цвет стоит занести в переменную

2024-10-06 18:27 UTC, VladToby commented on packages/client/src/pages/CreateThread/CreateThread.scss
> +    color: #797979;
Цвета стоит занести в переменные, и использовать конкретные переменные вместо `$c_black` и `$c_white`

2024-10-06 18:27 UTC, VladToby commented on packages/client/src/pages/Forum/Forum.scss
> +$title-color: #bebebe;
Думаю лучше перенести переменные в vars.scss

2024-10-06 18:27 UTC, VladToby commented on packages/client/src/pages/Thread/Thread.scss
> +      border-right: 1px solid #5e5e5e;
Цвет стоит занести в переменную

2024-10-06 18:27 UTC, VladToby commented on packages/client/src/pages/Thread/Thread.scss
> +          color: #797979;
Цвета стоит занести в переменные и лучше использовать конкретную переменную вместо `$c_black`

2024-10-06 18:27 UTC, VladToby commented on packages/client/src/pages/Thread/Thread.tsx
> +                <img className="author__avatar" src={UserAvatar} alt="Avatar" />
Думаю лучше использовать компонент Avatar. Сейчас наверно это бессмысленно, но стоит пометить в TODO чтобы не забыть изменить

2024-10-07 06:50 UTC, Timur233 approved these changes
Верстка просто отличная! 
У меня чуть-чуть комментов, они не критичные

2024-10-07 06:50 UTC, Timur233 commented on packages/client/src/components/ui/Pagination/Pagination.tsx
> +      index !== 0 ? ' compact-button_white' : ''
Чуть не понял тут логику, я думаю нужно принять в пропсах активную страницу, и по ней ориентироваться.

2024-10-07 06:50 UTC, Timur233 commented on packages/client/src/components/ui/Pagination/Pagination.tsx
> +        useFixWidth={false}></Button>
Кнопка "вперед" отображается если страница не последняя. А если не первая, можно отобразить кнопку "назад"

2024-10-07 06:50 UTC, Timur233 commented on packages/client/src/pages/CreateThread/CreateThread.scss
> +      min-height: 130px;
Можно задать, максимальную ширину, что бы при изменении размера пользователем не ломалась верстка.

2024-10-07 06:50 UTC, Timur233 commented on packages/client/src/pages/Thread/Thread.tsx
> +            <span>Ответить Timur233:</span>
Я тут подразумевал, что заголовок "Ответить" когда просто пишешь коммент, а "ответить login" когда нужно  ответить кому-то на сообщение. Давай пока оставим только "Ответить:", что бы вопросов не было.

2024-10-07 06:50 UTC, Timur233 commented on packages/client/src/pages/Forum/Forum.scss
> +  .threads {
А почему не &__threads {} ))

2024-10-07 06:50 UTC, Timur233 commented on packages/client/src/pages/Forum/Forum.scss
> +  .threads {
Между тредами и пагинацией можно чуть добавить отступа.

2024-10-07 10:41 UTC, shamemask approved these changes
Вроде всё отлично! Мне нечего добавить)

2024-10-07 14:21 UTC, k0ndratov commented on packages/client/src/components/ui/Pagination/Pagination.tsx
> +      index !== 0 ? ' compact-button_white' : ''
Даа, я так и планировал. Но тут типо реальной пагинации нет, и фиг знает какой в урле будет номер.

Это просто чтобы показать, как будет активный выглядеть.

Закину в TODO.

2024-10-07 14:23 UTC, k0ndratov commented on packages/client/src/components/ui/Pagination/Pagination.tsx
> +        useFixWidth={false}></Button>
Эту штуку хочется закинуть в логику пагинации уже. В рамках этой задачи даже не думал об этом.

2024-10-07 14:50 UTC, k0ndratov commented on packages/client/src/pages/Forum/Forum.scss
> +    background-image: url('@/assets/images/destroyed-tanks.png');
Понял, добавил для него z-index.

2024-10-07 15:07 UTC, k0ndratov commented on packages/client/src/pages/Thread/Thread.tsx
> +            <span>Ответить Timur233:</span>
Готово.

2024-10-07 15:08 UTC, k0ndratov commented on packages/client/src/pages/Forum/Forum.scss
> +  .threads {
Готово.

2024-10-07 15:19 UTC, k0ndratov commented on packages/client/src/pages/CreateThread/CreateThread.scss
> +      min-height: 130px;
Готово.

2024-10-07 15:26 UTC, k0ndratov commented on packages/client/src/pages/Thread/Thread.tsx
> +                <img className="author__avatar" src={UserAvatar} alt="Avatar" />
Компонент Avatar вроде имеет логику изменения себя. Как будто она тут лишняя. Или мб сделать атомарный компонет, который переиспользовать в Avatar и тут. Но тут уже хз, стоит ли оно того.

2024-10-07 15:30 UTC, k0ndratov commented on packages/client/src/pages/Thread/Thread.tsx
> +                <img className="author__avatar" src={UserAvatar} alt="Avatar" />
Ну и в TODO не уверен, так как не ясно, либо какой-то флаг для логики изменения делать, либо атомарный компонент.

2024-10-07 16:36 UTC, VladToby commented on packages/client/src/pages/Thread/Thread.tsx
> +                <img className="author__avatar" src={UserAvatar} alt="Avatar" />
Да, тут я что-то затроил, ты прав

2024-10-07 16:36 UTC, VladToby approved these changes

2024-10-08 07:25 UTC, kyzinatra commented on packages/client/src/components/ui/Pagination/Pagination.tsx
> +            onClick={() => navigate(`/forum/${index}`)}
Компоненты без `children` стоит закрывать сразу `<bUTTON />`

2024-10-08 07:26 UTC, kyzinatra commented on packages/client/src/pages/CreateThread/CreateThread.tsx
> +          name="first-comment"
Хорошая верстка

2024-10-08 07:26 UTC, kyzinatra approved these changes
Отличная работа! Понравилась верстка страниц. Круто, что выносите в переменные css-цвета. Вопросов по работе у меня нет, вы отлично постарались!

2024-10-08 08:21 UTC, merged