[SOK-20] leaderboard page
Timur233/falcon-tanks pull request #7
Opened 2024-09-27 04:44 UTC by k0ndratov

[### Какую задачу решаем](https://linear.app/sokoly/issue/SOK-20/sverstat-stranicu-liderborda)

### Скриншоты/видяшка (если есть)
![image](https://github.com/user-attachments/assets/a6b5eefb-b7fd-4872-a6ea-017367c28b8c)

### TBD (если есть)
Предполагаю что заголовок лучше сделать с помощью компонента PageTitle, для консистентности.

2024-09-27 10:16 UTC, Timur233 requested changes
Правки в основном по верстке. 
Я думаю нужно сделать заголовок как в макете, сейчас сделаю компонент, залью к себе. В течении 30мин

2024-09-27 10:16 UTC, Timur233 commented on packages/client/src/layouts/PrivateLayout/PrivateLayout.tsx
> +      <div className="private-layout__body">
Нужен отступ от шапки. Я делал 40px, можно и 20.

2024-09-27 10:16 UTC, Timur233 commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +    display: flex;
Сделай display: block. Я с начала даже подумал что это не изображение, а обертка, так как flex не влияет на тег img

2024-09-27 10:16 UTC, Timur233 commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +    <main className="container leaderboard-page">
Давай тег main вынесем в layout, а container сделай обыкновенным div. 
Я сейчас у себя в publicLayout'e тоже боди укажу как main тег

2024-09-27 10:16 UTC, Timur233 commented on packages/client/src/layouts/PrivateLayout/PrivateLayout.tsx
> +      <div className="private-layout__body">
Можно даже и сверху и снизу, что бы внизу появился воздух 
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/5f3c95a0-d399-4a14-a012-f5c7bbb9263c">

2024-09-27 10:16 UTC, Timur233 commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +        className="leaderboard-page__title"></PageTitle>
Я думаю тут все таки сделать дефолтный заголовок как в макете, вычурно получается. 
Я сейчас у себя этот компонент переименую в CustomPageTitle и добавлю новый компонент PageTitle, который будет рендерить простой заголовок. 
Затянешь еще раз мою ветку.

2024-09-27 10:16 UTC, Timur233 commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +              <div className="records__record-item record-item">
records__record-item - тавтология )) 
Можно просто сделать records__item

2024-09-27 10:16 UTC, Timur233 commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +                  <img src={PlayerAvatar} alt="Avatar" />
Добавь отдельный класс .user-info__avatar. 
При написании стилей лучше избегать использование вложенности.

2024-09-27 10:16 UTC, Timur233 commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +                  <img src={StarColor} alt="Медаль" />
Тоже вложенность, напиши отдельный класс .user-result__star.

2024-09-27 10:16 UTC, Timur233 commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +      &::before {
Не вижу смысла в использовании этого псевдо элемента, проще задать градиент элементу .gradient-wrapper. А сам класс элемента переименовать в .records__item-wrapper. 
Получится так: 
&__item-wrapper {
      position: relative;
      border-radius: 16px;
      background: linear-gradient(90deg, #adadad 52.5%, #474747 100%);
}

2024-09-27 10:16 UTC, Timur233 commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +      border-radius: 16px;
Внутрений радиус нужно сделать меньше. По моему 12px подходит.

2024-09-27 10:16 UTC, Timur233 commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +      background-color: #000;
Можно использовать переменную

2024-09-27 10:16 UTC, Timur233 commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +      padding: 19px;
Padding большой получился, сделай 8px 16px

2024-09-27 10:16 UTC, Timur233 commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +            <div className="gradient-wrapper">
Наверно правельнее сделать не gradient-wrapper а records__item-wrapper.

2024-09-27 10:16 UTC, Timur233 commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +        color: $text-color;
Цвет по макету #C5C5C5 и отступ снизу 4px

2024-09-27 10:16 UTC, Timur233 commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +        img {
По макету подразумевается бордер у изображения 
<img width="332" alt="image" src="https://github.com/user-attachments/assets/82d45f77-84b3-4ad8-8267-8a1a691abfff">

Тут еще есть проблема, что изображения в нашей АПИ не обязательно квадратные, то есть в итоге будут растягиваться, но я думаю пока на это забьем.

2024-09-27 10:28 UTC, Timur233 commented
Залил правки в свою ветку, подтяни к себе.

2024-09-27 12:30 UTC, k0ndratov commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +        color: $text-color;
А точно нам этот цвет нужен? Просто он вроде в единственном месте юзается, да и почти идентичен `#f8f8f8` который `$text-color`, не?

Я просто не могу ему константу придумать. Возможно просто воткнуть значение без константы тогда.

2024-09-27 12:33 UTC, k0ndratov commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +        img {
Слушай, а я не могу его почему-то вытащить без бордера. Выглядит так, что это общая картинка. Или я чета не понимаю?

![image](https://github.com/user-attachments/assets/decde06a-163a-4fbd-be81-98323242ec37)

2024-09-27 12:44 UTC, Timur233 commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +        color: $text-color;
Да нужен он как более приглушенный, создай переменную $text-color-muted. 
Можно было бы добавить переменную только в твой файл, но я думаю с форумом еще понадобится.

2024-09-27 12:44 UTC, Timur233 commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +        img {
Сейчас сделаю ассет.

2024-09-27 12:45 UTC, Timur233 commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +        img {
<img width="563" alt="image" src="https://github.com/user-attachments/assets/c037da9d-3a5c-461c-8d0b-af6f72a840ca">

2024-09-27 12:47 UTC, k0ndratov commented on packages/client/src/layouts/PrivateLayout/PrivateLayout.tsx
> +      <div className="private-layout__body">
Готов.

2024-09-27 12:47 UTC, k0ndratov commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +    display: flex;
Поправил.

2024-09-27 12:48 UTC, k0ndratov commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +    <main className="container leaderboard-page">
Готово.

2024-09-27 12:48 UTC, k0ndratov commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +        className="leaderboard-page__title"></PageTitle>
Ага, отлично село. Даже править не пришлось.

2024-09-27 12:51 UTC, k0ndratov commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +              <div className="records__record-item record-item">
Поправил.

2024-09-27 12:53 UTC, k0ndratov commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +                  <img src={PlayerAvatar} alt="Avatar" />
Попровал. А почему может стать проблемой? Я думал наоборот, все что обернуто классом блоком и можно застилить без класса, лучше так делать.

2024-09-27 12:53 UTC, k0ndratov commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +                  <img src={StarColor} alt="Медаль" />
Поправил.

2024-09-27 12:53 UTC, k0ndratov commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +      &::before {
Да, чета я с GPT намудрил тут. Поправил.

2024-09-27 12:53 UTC, k0ndratov commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +      border-radius: 16px;
Поправил.

2024-09-27 12:54 UTC, k0ndratov commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +      background-color: #000;
Поправил.

2024-09-27 12:54 UTC, k0ndratov commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +      padding: 19px;
Поправил.

2024-09-27 12:54 UTC, k0ndratov commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +            <div className="gradient-wrapper">
Поправил.

2024-09-27 12:54 UTC, k0ndratov commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +        color: $text-color;
Ага, понял. Окей.

2024-09-27 13:15 UTC, k0ndratov commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +        img {
Спасибо, поправил.

Но тут поймал нюанс, что дергается верстка при загрузке картинки. Поправил это установив им `height`. Хз, норм практика?

2024-09-28 08:32 UTC, Timur233 commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +        img {
Да вполне 👌

2024-09-28 10:20 UTC, Timur233 commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +                  <img src={PlayerAvatar} alt="Avatar" />
Читаемость стилей. И кейсы при которых может измениться вложенность или на этом уровне могут потребоваться другие изображения

2024-09-28 10:24 UTC, Timur233 commented on packages/client/src/pages/Leaderboard/Leaderboard.scss
> +      border-radius: 16px;
Сорри, я не правильно выразился. 
У .records__item-wrapper нужно оставить скругление 16px, а у .records__item сделать 12px, что бы рамка была ровная.

2024-09-28 10:25 UTC, Timur233 approved these changes
Все супер, только один коммент))

2024-09-28 13:09 UTC, merged