[SOK-16]
Timur233/falcon-tanks pull request #8
Opened 2024-09-27 05:38 UTC by gloginov

+add backendApi
+create axios interceptors
+add userReducer and create function for use yandex api +add env
*update SignIn.tsx for use backendApi
*update SignUp.tsx for use backendApi
*format and lint

### [Какую задачу решаем](https://linear.app/sokoly/issue/SOK-16/realizovat-logiku-avtorizacii)

2024-09-27 08:11 UTC, VladToby commented on packages/client/src/store/reducers/user-reducer.ts
> +  name: 'UserReducer',
Возможно стоит поменять на AuthReducer, с юзером будет связана другая логика (аватарка, изменение данных пользователя), которую сюда не стоит добавлять

2024-09-27 08:11 UTC, VladToby commented on packages/client/src/store/reducers/user-reducer.ts
> +    url: `${import.meta.env.VITE_AUTH_URL}/auth/user`,
Функции getUser, logoutUser, signInUser, и signUpUser используют `import.meta.env.VITE_AUTH_URL` в URL запросов. `baseUrl` уже установлен в backendApi.
Можно использовать `url: '/auth/user'`

2024-09-27 08:11 UTC, VladToby commented on packages/client/src/store/reducers/user-reducer.ts
> +    url: `${import.meta.env.VITE_AUTH_URL}/auth/logout`,
Можно использовать `url: '/auth/user'`

2024-09-27 08:11 UTC, VladToby commented on packages/client/src/store/reducers/user-reducer.ts
> +      url: `${import.meta.env.VITE_AUTH_URL}/auth/signin`,
Можно использовать `url: '/auth/user'`

2024-09-27 08:11 UTC, VladToby commented on packages/client/src/store/reducers/user-reducer.ts
> +      url: `${import.meta.env.VITE_AUTH_URL}/auth/signup`,
Можно использовать `url: '/auth/user'`

2024-09-27 08:39 UTC, gloginov commented on packages/client/src/store/reducers/user-reducer.ts
> +  name: 'UserReducer',
Переименовал

2024-09-27 08:39 UTC, gloginov commented on packages/client/src/store/reducers/user-reducer.ts
> +    url: `${import.meta.env.VITE_AUTH_URL}/auth/user`,
Точно!

2024-09-27 08:39 UTC, gloginov commented on packages/client/src/store/reducers/user-reducer.ts
> +    url: `${import.meta.env.VITE_AUTH_URL}/auth/logout`,
Точно!

2024-09-27 08:40 UTC, gloginov commented on packages/client/src/store/reducers/user-reducer.ts
> +      url: `${import.meta.env.VITE_AUTH_URL}/auth/signin`,
Точно!

2024-09-27 08:40 UTC, gloginov commented on packages/client/src/store/reducers/user-reducer.ts
> +      url: `${import.meta.env.VITE_AUTH_URL}/auth/signup`,
Точно!

2024-09-27 08:42 UTC, VladToby approved these changes

2024-09-27 10:44 UTC, k0ndratov reviewed
Крутая работа.

Оставил пару моментов, которые меня волнуют.

2024-09-27 10:44 UTC, k0ndratov commented on packages/client/src/layouts/private-layout.tsx
> +    if (user === null) {
Возможно чуть более безопаснее было бы `if (!user)`, чтобы захватить еще всякие undefined, "" и т.д...

2024-09-27 10:44 UTC, k0ndratov commented on packages/client/src/layouts/private-layout.tsx
> +  return user === null ? <h1>Загрузка...</h1> : <Outlet />
Выглядит так, что если запрос не пройдет, то будет бесконечно "Загрузка...". Возможно стоит при ошибке в backendApi перебрасывать на `<Error>`, чтобы хотя бы понятно было, что дальше нет смысла ждать.

2024-09-27 10:44 UTC, k0ndratov commented on packages/client/src/store/reducers/user-reducer.ts
> +export type UserType = {
Может такую штуку использовать?

`type Nullable<T> = T | null`

2024-09-27 10:44 UTC, k0ndratov commented on packages/client/src/store/reducers/user-reducer.ts
> +        window.location.href = '/'
А нельзя с помощью роутера перебросить, чтобы не ломать spa?

2024-09-27 10:44 UTC, k0ndratov commented on packages/client/src/store/reducers/user-reducer.ts
> +        window.location.href = '/'
И еще момент, я не разбираюсь в реакте. Нормально ли, что redux управляет редиректами? Я просто думал, что его задача исключительно управлять состоянием приложения. А тут получается что он начинает реализовывать это состояние.

Или я тут заблуждаюсь?

2024-09-27 10:44 UTC, k0ndratov commented on packages/client/src/api/backendApi.ts
> +      window.location.href = '/sign-in?redirectUrl=' + window.location.pathname
Может быть можно роутером перебросить?

2024-09-27 10:44 UTC, k0ndratov commented on packages/client/src/api/backendApi.ts
> +    if (axios.isCancel(error)) return Promise.reject(error)
А есть смысл в этом условии, если все равно возвращается тоже самое?

2024-09-27 10:44 UTC, k0ndratov commented on packages/client/src/api/backendApi.ts
> +      localStorage.removeItem('user')
Возможно не стоит давать backendApi возможность манипулировать localStorage`ем? Начинаем как будто смешивать логику запросов и управления состоянием.

Возможно стоит сделать какой-то errorHandler, который опознает ошибку и вызовет нужный контролер.

2024-09-27 10:44 UTC, k0ndratov commented on packages/client/src/api/backendApi.ts
> +      window.location.href = '/sign-in?redirectUrl=' + window.location.pathname
И возможно тоже смешивается логика. Теперь получается, что backendApi управляет роутами и локал сторажем. Как будто много на себя берет, не?

2024-09-27 10:44 UTC, k0ndratov commented on packages/client/src/components/ui/Button/Button.tsx
> +  href?: string | undefined
Не будет чуть путацины с href`ом для кнопки? Вроде ожидается, что кнопка делает экшены, а ссылки перебрасывают.

2024-09-27 10:56 UTC, gloginov commented on packages/client/src/layouts/private-layout.tsx
> +    if (user === null) {
Тут переменная user объявлена с типом, и по идее туда не может попасть объект другого типа, будет ошибка типизации. Тут думаю оставить так ведь если теоретически будет undefined тогда будет ошибка типов.

2024-09-27 11:18 UTC, gloginov commented on packages/client/src/api/backendApi.ts
> +      localStorage.removeItem('user')
Манипуляцию localstorage уберу

2024-09-27 11:20 UTC, gloginov commented on packages/client/src/api/backendApi.ts
> +      window.location.href = '/sign-in?redirectUrl=' + window.location.pathname
Он берет на себя одну функцию - отловить 401 (что говорит о том что авторизация слетела) и что-то сделать. Подумаю как оформить

2024-09-27 11:22 UTC, gloginov commented on packages/client/src/components/ui/Button/Button.tsx
> +  href?: string | undefined
Тут ты наверно прав. Уберу href оставлю только событие

2024-09-28 11:21 UTC, Timur233 requested changes
Привет! Отличная работа! Сейчас попробую затянуть к себе и сделать кнопку "профиль" в шапке, с именем пользователя )) 
 
 У меня пара комментов:
- Давай запретим посещение страниц, авторизации и регистрации авторизованным пользователям. 
- И я бы убрал ненужные комментарии в коде, пример ниже.

// if user is empty call backend
if (user === null) { dispatch(getUser()) }

2024-09-28 11:21 UTC, Timur233 commented on packages/client/src/layouts/private-layout.tsx
> +      dispatch(getUser())
Обратил внимание, что при загрузке страницы запрос улетает 2 раза подряд.
<img width="1078" alt="image" src="https://github.com/user-attachments/assets/b96459a9-424a-422f-896e-19eb85aa76f7">

2024-09-28 11:21 UTC, Timur233 commented on packages/client/src/layouts/private-layout.tsx
> +  return user === null ? <h1>Загрузка...</h1> : <Outlet />
Он кидает на авторизацию при неудачном запросе, сделаю компонент прелоадера для таких целей.

2024-09-28 11:21 UTC, Timur233 commented on packages/client/src/api/backendApi.ts
> +      window.location.href = '/sign-in?redirectUrl=' + window.location.pathname
Чуть смущает camelCase в гет параметрах. Это не правка, просто коммент.

2024-09-29 03:25 UTC, gloginov commented on packages/client/src/layouts/private-layout.tsx
> +      dispatch(getUser())
Дважды улетает только в dev из-за strict mode
https://legacy.reactjs.org/docs/strict-mode.html

2024-09-30 03:40 UTC, Timur233 approved these changes

2024-10-01 16:34 UTC, gloginov commented on packages/client/src/api/backendApi.ts
> +      window.location.href = '/sign-in?redirectUrl=' + window.location.pathname
Убрал вообще этот код. Сделал иначе

2024-10-01 16:35 UTC, gloginov commented on packages/client/src/api/backendApi.ts
> +    if (axios.isCancel(error)) return Promise.reject(error)
Убрал

2024-10-01 16:35 UTC, gloginov commented on packages/client/src/api/backendApi.ts
> +      window.location.href = '/sign-in?redirectUrl=' + window.location.pathname
Переделал на роутер

2024-10-01 16:36 UTC, gloginov commented on packages/client/src/store/reducers/user-reducer.ts
> +        window.location.href = '/'
Наверно не нормально. Переделал, логика в компоненте

2024-10-01 16:36 UTC, gloginov commented on packages/client/src/store/reducers/user-reducer.ts
> +export type UserType = {
Не стал использовать. Не понимаю в чем преимущество. Поясни

2024-10-01 22:43 UTC, k0ndratov approved these changes

2024-10-02 09:38 UTC, MikeDevice approved these changes
Ты молодец. Большая работа и это действительно сложная задачка. Описал всякие нюансы, как можно сделать лучше, но критических замечаний нет.

Вообще глобальная рекомендация:
1. Из реакт компонента кидать один экшн `dispatch(login())`, например, а в санке уже ловить этот экшн и отправлять запросы на сервер там. Так логика будет чище.
2. Ну и меньше копипасты и больше обобщений!

2024-10-02 09:38 UTC, MikeDevice commented on package-lock.json
Интересно, что у вас в проекте есть и package-lock, и yarn.lock. Обычно используется что-то одно из двух. Возможно, у вас в команде кто-то устанавливает зависимости через `npm install`, а кто-то через `yarn`. Нужно разобраться с этим придти к единообразию.

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/api/backendApi.ts
> +  baseURL: import.meta.env.VITE_AUTH_URL,
Круто, что такие штуки унесены в переменные окружения 👍

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/api/backendApi.ts
> +  baseURL: import.meta.env.VITE_AUTH_URL,
Отдельный лайк за абстракцию в виде `backendApi`, а не использование чистого `axios` во всех местах

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/app/App.test.tsx
> +// import App from './App'
А что тут такое? Почему ты закоментил? Этот тест сейчас не запускается никогда?

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/components/ui/Button/Button.tsx
> +  href?: string | undefined
Хороший поинт от @k0ndratov 👍

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/components/ui/Button/Button.tsx
> +  onClick?: (() => Promise<void>) | (() => any) | undefined
ESlint не зря ругается. Лучше вместо  any использовать `unknown`, а ещё лучше чётко прописывать нужный тип.

Пытаюсь понять, а зачем три типа подаёшь? Смотри, так как у тебя после `onClick` идёт вопросительный знак, значит тип `undefined` можно смело удалить, останется два, но всё равно не пойму, зачем тут промис.

Ты просто кидаешь в button функцию onClick. Нативная кнопка промис не возвращает.

**Нужно исправить это** Вообще любой такой onClick обычно имеет тип `(): void` или такой же, только с параметром `event` внутри

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/layouts/AuthLayout/AuthLayout.tsx
> +        autoClose: 1500,
**можно лучше:** желательно такие числа выносить вверх файла в качестве констант

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/layouts/private-layout.tsx
> +  const dispatch = useAppDispatch()
**можно лучше:** Строки с определением `userIsLogged` такие же, как и в файле AuthLayout. Рекомендую написать хук `useIsUserLogged`, который бы содержал эту логику и использовать его во всех таких местах.

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/layouts/private-layout.tsx
> +    }
**Можно лучше:** тут в этом `useEffect` много намешано разных логик: логика получения данных с сервера, логика авторизации юзера на клиенте и логика рисования интерфейса (тосты). По хорошему так смешивать не нужно и разносить это по файлам.

Всё, что связано с полужением данных уносить в редаксовые thunk, а штуки с sessionStorage -- в какие-нибудь хелперы

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/pages/Profile/Profile.tsx
> +      window.sessionStorage.setItem('userIsLogged', '0') // 0
**Можно лучше:** копипаста того, что было выше. Лучше вынести в хелпер.

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/pages/Profile/Profile.tsx
> +      <button onClick={() => onLogoutUser()}>Выйти</button>
**Можно лучше:**
```suggestion
      <button onClick={onLogoutUser}>Выйти</button>
```

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/pages/SignIn/SignIn.tsx
> +        }}>
**Можно лучше:** наверняка это будет не единственная форма на проекте, потому рекомендую завести компонент Form, который бы внутри себя содержал базу для формы, включая в себя этот `e.preventDefault()`

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/pages/SignIn/SignIn.tsx
> +          onClick={() => handleSubmit()}
```suggestion
          onClick={handleSubmit}
```

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/pages/SignUp/SignUp.tsx
> +          e.preventDefault()
Ааа, ну вот и подтверждение моим словам выше.

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/pages/SignUp/SignUp.tsx
> +  }
**Можно лучше:** этот файл очень похож на файл signIn. Рекомендую вынести общую логику в хук.

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/pages/SignUp/SignUp.tsx
> +          onClick={() => handleSubmit()}
```suggestion
          onClick={handleSubmit}
```

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/pages/SignUp/SignUp.tsx
> +          useFixWidth={true}
```suggestion
          useFixWidth
```

Можно просто без `true`

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/store/index.ts
> +  AuthReducer,
**Можно лучше:** обычно пишут с маленькой буквы:
```suggestion
  authReducer: AuthReducer,
```

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/store/index.ts
> +  : never
Воу! прикольно! 👍

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/store/reducers/auth-reducer.ts
> +  user: null as unknown as UserType,
так обычно плохо делать. Лучше создать тип:

```tsx
type InitialState = { user: UserType | null }
const initialState:  InitialState  = { ... }
```

2024-10-02 09:38 UTC, MikeDevice commented on packages/client/src/store/reducers/auth-reducer.ts
> +export default AuthReducer
**Можно лучше:** Все санки похожи между собой. Рекомендую написать базовый санк, который ба содержал в себе обработку ошибок, и потом его использовать во всех местах.

2024-10-02 10:39 UTC, merged